spring:

  datasource:
    url: jdbc:h2:mem:cards_db;MODE=PostgreSQL
    username: sa
    password: password
    driverClassName: org.h2.Driver

  flyway:
    enabled: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    ddl-auto: create-drop
